### ISSUE TITLE
Update npm version in CI to publish packages in workflows

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#129]
## Describe the bug
The Issue [...You need to authorize this machine using 'npm adduser'](https://github.com/npm/cli/issues/2453) which was caused in the github workflow on `npm publish` should be resolved now.
Try to update the temporary fix from https://github.com/dlr-eoc/ukis-frontend-libraries/pull/90#issuecomment-879855928 with a current npm version `> v8.5.1.`  

https://github.com/dlr-eoc/ukis-frontend-libraries/blob/99d2f8e0138c0120887c827c8a7983a1de0c63a1/.github/workflows/package-main-release.yml#L187

https://github.com/dlr-eoc/ukis-frontend-libraries/blob/99d2f8e0138c0120887c827c8a7983a1de0c63a1/.github/workflows/package-pre-release.yml#L69

- [Node Releases](https://nodejs.org/en/download/releases/)
- [Angular Node compatiblity](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3)

**Comment by boeckMt** [comment]
See issue https://github.com/npm/cli/issues/3573

now using node 16 and npm >8.19

```yml
...
 - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@dlr-eoc"
      - run: npm ci
      - run: npm i -g npm@8.19.2
      - run: |
          ...
              npm publish "$dir" --access public
          ...
```
