### ISSUE TITLE
Use NPM 7 and workspaces

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#55]
## Description
To better handle dependencies management try to use NPM 7 workspaces with the monorepo.

https://docs.npmjs.com/cli/v7/using-npm/workspaces

**Comment by boeckMt** [comment]
For this we also have to update the github actions to use node 15.x https://github.com/actions/setup-node/issues/213#issuecomment-739685886
```
// https://github.com/actions/setup-node
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '15'
```
