### ISSUE TITLE
Enhancements of layer-control

### ISSUE THREAD

**Issue by boeckMt** [dlr-eoc/ukis-frontend-libraries#69]
## Description
- Add possibility to hide Layers/Groups in `@dlr-eoc/layer-control` without removing them from the `LayersService`.
- Allow dynamic Angular Components for Groups (like for Layers with action?: IDynamicComponent) // https://github.com/dlr-eoc/ukis-frontend-libraries/issues/12

## Relevant Package
- [@dlr-eoc/layer-control](https://github.com/dlr-eoc/ukis-frontend-libraries/tree/master/projects/layer-control)
- [@dlr-eoc/services-layers](https://github.com/dlr-eoc/ukis-frontend-libraries/tree/master/projects/services-layers)

### Describe alternatives you've considered
Set the Layer/Group [cssClass property](https://github.com/dlr-eoc/ukis-frontend-libraries/blob/v7.3.0-next.0/projects/services-layers/src/lib/types/Layers.ts#L131) and then hide the item with style

```scss

::ng-deep ukis-layerentry-group.hide {
   height: 0;
   margin: 0;
   padding: 0;
   border: none;
   visibility: hidden;
   z-index: -1;
}
```
